openapi: 3.0.3
info:
  title: Library API
  version: 1.0.0
  description: STD22083
servers:
  - url: https://library.com
paths:
  
  /authors:
    get:
      summary: Get all authors
      description: The returned authors are ordered by updated datetime.
      operationId: getAuthors
      parameters:
        - in: query
          name: bookName
          description: Filter return authors by given name
          required: false
          schema:
            type: string
        - in: query
          name: releaseDateStart
          description: Filter authors by release date (start of interval)
          required: false
          schema:
            type: string
            format: date
        - in: query
          name: releaseDateEnd
          description: Filter authors by release date (end of interval)
          required: false
          schema:
            type: string
            format: date
      responses:
        200:
          description: The list of filtered authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      summary: Create or update a list of authors
      operationId: crupdateAuthors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      responses:
        200:
          description: The list of created or updated authors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    delete:
      summary: Delete authors by name
      operationId: deleteAuthorsByName
      parameters:
        - in: query
          name: bookName
          description: Filter authors by name
          required: false
          schema:
            type: string
      responses:
        200:
          description: authors have been deleted

  #TODO2: complete GET (can be filtered by name) - PUT - DELETE
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        sex:
          #TODO1: set it as a component with properties : id, name, sex (M or F)
          type: string